spring:
  cloud:
    gateway:
      routes:
      - id: work-plan
        uri: http://localhost:7010/
        predicates:
          - Path=/plan/**
  # 数据源配置
  datasource:
    #通用数据源配置
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/work_plan?charset=utf8mb4&useSSL=false
    url: jdbc:mysql://211.149.208.58:3306/hisuser_noah?charset=utf8mb4&useSSL=false
    username: root
#    password: 753951
    password: 100wit.com
    # Hikari 数据源专用配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  # JPA 相关配置
  jpa:
    # 设置默认存储引擎为InnoDB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update